---
- name: Remove old Grafana repo
  file:
    path: /etc/yum.repos.d/grafana.repo
    state: absent

- name: Clean package manager cache
  command: dnf clean all
  changed_when: false

- name: Install dependencies
  dnf:
    name:
      - wget
    state: present
    update_cache: yes

- name: Add Grafana repository
  yum_repository:
    name: grafana
    description: Grafana official YUM repository
    baseurl: https://rpm.grafana.com
    gpgcheck: yes
    gpgkey: https://rpm.grafana.com/gpg.key
    enabled: yes

- name: Install Grafana
  dnf:
    name: grafana
    state: present

- name: Start Grafana
  systemd:
    name: grafana-server
    enabled: yes
    state: started