---
- name: Update system
  dnf:
    name: "*"
    state: latest
    update_cache: yes

- name: Install base packages
  dnf:
    name:
      - curl
      - wget
    state: present
    allowerasing: yes
